default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: bootstrap_development
  #username: bootstrap
  #password:
  #host: localhost
  #port: 5432

test:
  <<: *default
  database: bootstrap_test

production:
  <<: *default
  database: bootstrap_production
  username: bootstrap
  password: <%= ENV['BOOTSTRAP_DATABASE_PASSWORD'] %>
